# coding: utf8

db.define_table('questionnaire',
                Field('auth_user_ref', db.auth_user, required=True, default=auth.user_id, readable=False, writable=False, unique=True),
                Field('question001', 'string',label="Name of Venue"),
                Field('question002', 'string', label="Address of Venue"),
                Field('question003', 'string', label="Venue Contact Phone Number"),
                Field('question004', 'boolean', default=False, label="Check if your location is accessible to people with impaired mobility?"),
                Field('question005', 'boolean', default=False, label="Check if you have hosted a ChiPy meeting before?"),
                Field('question006', 'boolean', default=False, label="Check if you have attended ChiPy before?"),
                Field('question007', 'boolean', default=False, label="Check if you have room for 50 to 90 people?"),
                Field('question008', 'boolean', default=False, label="Check if you can sponsor food?"),
                Field('question009', 'boolean', default=False, label="Check if an RSVP list is required?"),
                Field('question010', 'string', label="What time can we show up to prepare for the meeting?"),
                Field('question011', 'string', label="How long can we stay in the room?"),
                Field('question012', 'text', label="Are you located near public transportation? If yes, please explain"),
                Field('question013', 'text', label="Is there convenient parking near your location? If yes, please explain"),
                Field('question014', 'boolean', default=False, label="Check if you can provide a table or 2 in back for food and drinks?"),
                Field('question015', 'boolean', default=False, label="Check if you can provide garbage and recycling for food and drinks?"),
                Field('question016', 'string', label="Please supply contact information for the venue host organizers"),
                Field('question017', 'boolean', default=False, label="Presenter: Podium - Something for the presenter to stand behind and put their laptop on"),
                Field('question018', 'boolean', default=False, label="Presenter: VGA Monitor on a small table near the podium - what is being displayed by the projector."),
                Field('question019', 'boolean', default=False, label="Presenter: Power to podium so the laptop doesn't have to run on batteries"),
                Field('question020', 'boolean', default=False, label="Presenter: 15 pin VGA cable from podium to projector.  (not HDMI)"),
                Field('question021', 'boolean', default=False, label="Presenter: Projector and screen"),
                Field('question022', 'boolean', default=False, label="PA System: Amp and speakers - built in or freestanding."),
                Field('question023', 'boolean', default=False, label="PA System: Wireless headset - presenters will typically type, it is hard to hold a mic and type"),
                Field('question024', 'boolean', default=False, label="PA System: Hand held mic"),
                Field('question025', 'boolean', default=False, label="PA System: Unbalanced audio input from laptop - if presenter wants to broadcast laptop audio"),
                Field('question026', 'boolean', default=False, label="Recording Station: Front Of House table 30' from podium (This is where the recording will happen.)"),
                Field('question027', 'boolean', default=False, label="Recording Station: Is table big enough for 2 people with laptops (required)"),
                Field('question028', 'boolean', default=False, label="Recording Station: Power to the table"),
                Field('question029', 'boolean', default=False, label="Recording Station: Balanced line level between PA and table"),
                Field('question030', 'boolean', default=False, label="Recording Station: Wired ethernet from podium to table"),
                Field('question031', 'boolean', default=False, label="Recording Station: wired Internet connection  - 1.8mbs for streaming. (optional)"),
                Field('question032', 'string', label="Misc: Where can AV equipment be unloaded?"),
                Field('question033', 'boolean', default=False, label="Misc: Check if you can provide volunteers to meet us to help unload equipment?"),
                Field('question034', 'string', label="Misc: What are loading doc hours?"),
                Field('question035', 'string', label="Misc: Who is a contact for the loading doc?"),
                Field('question036', 'string', label="Misc: Where can a jeep SUV be parked during the meeting? The jeep is used to bring equipment."),
                Field('other_information', 'text', label="Is there anything else you wish to share or any answers you wish to explain?")
                )
